### ISSUE TITLE
Where is the porting?

### ISSUE THREAD

**Issue by georgeanderson** [RISC-OS-Community/LibCJSON#1]
# Background

I don't see any source on this repo. Is this a placeholder for the port or I am missing something?

Thanks!

**Comment by pzaino** [comment]
Hi @georgeanderson ,
sorry for the very late reply, I had other things to complete before finishing this one.

All the code is now in the Main repsoritory and builds fine with both GNU GCC on RISC OS and Acorn/ROOL DDE.

It should also build on old Archimedes/RiscPC Acorn DDE, but I had no time to test it.

Hope this helps, please let me know if everything works fine on your system!

Thanks,
